CREATE TABLE IF NOT EXISTS `common-configs` (
  id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '公共配置表主键ID',
  ai_enabled BOOLEAN DEFAULT FALSE COMMENT '是否启用AI聊天功能',
  ranking_enabled BOOLEAN DEFAULT FALSE COMMENT '是否启用群聊排行榜功能',
  summary_enabled BOOLEAN DEFAULT FALSE COMMENT '是否启用聊天记录总结功能',
  welcome_enabled BOOLEAN DEFAULT FALSE COMMENT '是否启用新成员加群欢迎功能',
  chat_url VARCHAR(255) DEFAULT '' COMMENT '聊天AI的基础URL地址',
  chat_key VARCHAR(255) DEFAULT '' COMMENT '聊天AI的API密钥',
  chat_model VARCHAR(100) DEFAULT '' COMMENT '聊天AI使用的模型名称',
  chat_persona TEXT COMMENT '聊天AI的人设配置',
  summary_model VARCHAR(100) DEFAULT '' COMMENT '聊天总结使用的AI模型名称',
  image_url VARCHAR(255) DEFAULT '' COMMENT '绘图AI的基础URL地址',
  image_key VARCHAR(255) DEFAULT '' COMMENT '绘图AI的API密钥',
  image_secret VARCHAR(255) DEFAULT '' COMMENT '绘图AI的API密钥secret',
  image_model VARCHAR(100) DEFAULT '' COMMENT '绘图AI使用的模型名称',
  image_scheduler VARCHAR(100) DEFAULT '' COMMENT '绘图AI的请求调度配置',
  news_enabled BOOLEAN DEFAULT FALSE COMMENT '是否启用每日早报功能',
  news_cron VARCHAR(100) DEFAULT '' COMMENT '每日早报的定时任务表达式',
  friend_sync_enabled BOOLEAN DEFAULT FALSE COMMENT '是否启用好友同步功能',
  friend_sync_cron VARCHAR(100) DEFAULT '' COMMENT '好友同步的定时任务表达式',
  group_summary_enabled BOOLEAN DEFAULT FALSE COMMENT '是否启用群聊总结功能',
  group_summary_cron VARCHAR(100) DEFAULT '' COMMENT '群聊总结的定时任务表达式',
  morning_enabled BOOLEAN DEFAULT FALSE COMMENT '是否启用早安问候功能',
  morning_cron VARCHAR(100) DEFAULT '' COMMENT '早安问候的定时任务表达式',
  ranking_cron VARCHAR(100) DEFAULT '' COMMENT '群聊排行榜的定时任务表达式'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;