services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    networks:
      - wechat-robot
    ports:
      - '6379:6379'
    environment:
      REDIS_PASSWORD: houhou
    command: [ "redis-server", "--requirepass", "houhou" ]

  mysql:
    image: "${REGISTRY:-docker.io}/mysql:latest"
    restart: always
    container_name: mysql
    ports:
      - '3306:3306'
    environment:
      TZ: Asia/Shanghai # 设置时区
      MYSQL_ROOT_PASSWORD: 'houhou'

networks:
  wechat-robot:
    external: true
